CREATE DATABASE IF NOT EXISTS TortasFlash;

USE TortasFlash;

CREATE TABLE IF NOT EXISTS MENU(
IDMENU INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
FOODS VARCHAR(100),
DESERTS VARCHAR(100),
DRINKS VARCHAR(100)
);
 
CREATE TABLE IF NOT EXISTS LOCATION(
IDLOCATION INT PRIMARY KEY NOT NULL AUTO_INCREMENT
);

CREATE TABLE IF NOT EXISTS SCHEDULLE(
IDSCHEDULLE INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
DAY VARCHAR(100),
HOUR VARCHAR(100)
);
