CREATE DATABASE IF NOT EXISTS TortasFlash;

USE TortasFlash;

CREATE TABLE IF NOT EXISTS MENU(
TF INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
TORTAS VARCHAR(100)
);
 
CREATE TABLE IF NOT EXISTS LOCATION(
TFLOCATION INT PRIMARY KEY NOT NULL AUTO_INCREMENT
);

CREATE TABLE IF NOT EXISTS SCHEDULLE(
TFSCHEDULLE INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
`DAY` VARCHAR(100),
`HOUR` VARCHAR(100)
);